servers:
  production:
    host: "your-server-ip"
    username: "deploy"
    key_file: "~/.ssh/deployment_key"

applications:
  datablox-main:
    url: "https://datablox.com"
    health_check_url: "https://datablox.com/api/health"

monitoring:
  check_interval: 60
  enabled: true

alerts:
  email:
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    username: "your-email@gmail.com"
    password: "your-app-password"
    from: "alerts@datablox.com"
    to: "admin@datablox.com"
  
  alerts:
    - name: "High CPU Usage"
      condition: "cpu_high"
      threshold: 80.0
      duration: 300
      enabled: true
    - name: "Application Down"
      condition: "app_down"
      threshold: 0
      duration: 60
      enabled: true